### ISSUE TITLE
I seem to be getting an unexpected BAD_AUTH error.

### ISSUE THREAD

**Issue by stereotypicaldev** [CBenni/modlogsbot#8]
My config looks like this

 "pubsub_server": "wss://pubsub-edge.twitch.tv/v1",
        "mod": {
            "name": "name of my twitch account (procured by my twitch URL)",
            "id": "my twitch user id",
            "oauth": "an access token procured by the https://twitchtokengenerator.com/"

Discord Bot Connects just fine and I can send commands to it but I still get this : PubSub #0 received message: {"type":"RESPONSE","error":"ERR_BADAUTH","nonce":""} , I am doing something wrong?

**Comment by CBenni** [comment]
Make sure you dont have the `oauth:` in front of the auth token, iirc twitchtokengenerator prepends it to your token.

**Comment by stereotypicaldev** [comment]
That seems to have fixed the problem, I double checked everything else including the discord channel ID to make sure I haven't done anything wrong on my part. I am quite sure the program is listening for mod actions from twitch cause "Got a channel modlog for channel [id] for 1 listeners" shows and the connection to PUBSUB is going back and forth. But I am getting a "An error occurred processing your request: no id returned o.O" on Discord. What do you think I might be getting wrong here?

The error I am getting is : 

/modlogsbot/index.js:389
					var discordchannel = client.channels.find("id", listener.discord.channel_id);
					                                     ^

TypeError: client.channels.find is not a function

**Comment by ALazyMeme** [comment]
Try git pulling the bot with the latest changes. I've moved it over to helix, so it should work just fine now 🤞🏿
